platform :ios, '9.0'

target 'PolyvRNCloudClassDemo' do
  use_frameworks!

  pod 'Masonry', '~> 1.1.0'
  pod 'SDWebImage', '4.4.0'
  pod 'PolyvCloudClassSDK', '0.16.2'

  # 执行 npm install 命令之后，有可能会自动生成下面这两行配置，需要把这两行配置删掉或者注释掉
  # pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  # pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end
